Ride-The-Lightning/RTL

controllers/authenticate.js
routes/authenticate.js

Attempt to fix https://github.com/ShahanaFarooqui/RTL/issues/58

WIP: Make sure the browser does not show the access-key in the logs

---

app.js
common.js
connect.js
controllers/authenticate.js
package-lock.json
package.json
routes/authenticate.js

Make sure the browser does not show the access-key in the history

---

controllers/authenticate.js

Somehow, this does not work. But we don't really care about it actually.

Remove cookie signature

---

README.md
RTL_TOR_setup.md

Add documentation for serving remote RTL connections over Tor

---

docs/LNDAPICoverage.md

Based on api.lightning.community

Update LND API Coverage

---

README.md

This update fixes a broken hyperlink on README.md.

Fixed link to application configurations doc

---

src/app/app.component.html

make it easier for people who are not sure if this is the public key

feat: add tooltip to publickey div

---

common.js
connect.js
docs/Application_configurations
docs/RTL_setups.md
rtl.js

Configurable server host #303

---

controllers/RTLConf.js
controllers/authenticate.js
controllers/c-lightning/balance.js
controllers/c-lightning/channels.js
controllers/c-lightning/fees.js
controllers/c-lightning/getInfo.js
controllers/c-lightning/invoices.js
controllers/c-lightning/message.js
controllers/c-lightning/network.js
controllers/c-lightning/onchain.js
controllers/c-lightning/payments.js
controllers/c-lightning/peers.js
controllers/lnd/balance.js
controllers/lnd/channels.js
controllers/lnd/channelsBackup.js
controllers/lnd/fees.js
controllers/lnd/getInfo.js
controllers/lnd/graph.js
controllers/lnd/graphInfo.js
controllers/lnd/invoices.js
controllers/lnd/lndConfSettings.js
controllers/lnd/loop.js
controllers/lnd/message.js
controllers/lnd/newAddress.js
controllers/lnd/payReq.js
controllers/lnd/payments.js
controllers/lnd/peers.js
controllers/lnd/switch.js
controllers/lnd/transactions.js
controllers/lnd/wallet.js

Remove macaroon info before logging #306

Remove macaroon info before logging #306

---

rtl.js

This makes it easier to run the service just by running ./rtl.js

Added hashbang

---

README.md

Documentation: Full node Bitcoin and Lightning Network of BGeometrics included

Add Bitcon full node BCubium

---

controllers/eclair/channels.js
controllers/eclair/peers.js

ECL missing Alias on Channels page #429

ECL missing Alias on Channels page #429

---

controllers/RTLConf.js

Updated error message for download backup #471

Updated error message for download backup #471

---

controllers/eclair/channels.js
package-lock.json
package.json
src/environments/version.ts

Channel Force Close #523

---

app.js

Increased request body size #544

Increased request body size #544

---

src/app/clightning/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.html
src/app/clightning/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.scss
src/app/clightning/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.ts
src/app/eclair/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.html
src/app/eclair/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.scss
src/app/eclair/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.ts

Channel mobile view update

---

controllers/shared/RTLConf.js

Mask config file passwords #636

Mask config file passwords #636

---

controllers/lnd/peers.js

LND Connect Peer Bug Fix #778

---

controllers/lnd/getInfo.js
routes/connect.js

Bug fix Empty channel backup #814

Bug fix Empty channel backup #814

---

controllers/c-lightning/getInfo.js

fixes: https://github.com/Ride-The-Lightning/RTL/issues/864

add signet to c-lightning getinfo

---

controllers/lnd/payments.js
docker/README.md

Adding stand alone docker run command to docker README.

Update README.md - reduce 1,000,000 payments to 100,000

---

src/app/clightning/home/channel-capacity-info/channel-capacity-info.component.html
src/app/clightning/home/channel-liquidity-info/channel-liquidity-info.component.html
src/app/clightning/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.ts
src/app/eclair/home/channel-capacity-info/channel-capacity-info.component.html
src/app/eclair/home/channel-liquidity-info/channel-liquidity-info.component.html
src/app/eclair/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.ts
src/app/lnd/home/channel-capacity-info/channel-capacity-info.component.html
src/app/lnd/home/channel-liquidity-info/channel-liquidity-info.component.html
src/app/lnd/peers-channels/channels/channels-tables/channel-open-table/channel-open-table.component.ts

Reverts Ride-The-Lightning/RTL#938

Revert "Channel linking from Dashboard to Open channels page"

---

backend/utils/config.js
server/utils/config.ts

Removed multipass check with SSO

Removed multipass check with SSO

---

src/app/clightning/routing/failed-transactions/failed-transactions.component.html
src/app/clightning/routing/failed-transactions/failed-transactions.component.ts

PR for https://github.com/Ride-The-Lightning/RTL/issues/936
Added out channel column along with the in channel column in failed transactions page: /rtl/cl/routing/failedtransactions

Added outgoing channel to failed transactions page

---

backend/controllers/eclair/fees.js
server/controllers/eclair/fees.ts

ECL Missing fee calculation on Dashboard #975

ECL Missing fee calculation on Dashboard #975

---

backend/utils/app.js
server/utils/app.ts

Adding CSRF Header for Browser Extension

Adding CSRF Header for Browser Extension

---

.circleci/config.yml

Removing multiarch

---

backend/controllers/shared/RTLConf.js
server/controllers/shared/RTLConf.ts

Hide rpcuser value from ln config #861

Hide rpcuser value from ln config #861

---

backend/utils/common.js
server/utils/common.ts

Updated error handling function

Updated error handling function

---

.github/README.md
.github/docs/Application_configurations.md
.github/docs/Core_lightning_setup.md
.github/docs/Eclair_setup.md
.github/docs/Multi_node_setup.md
.github/docs/RTL_setups.md
Sample-RTL-Config.json
backend/utils/app.js
backend/utils/common.js
backend/utils/config.js
backend/utils/database.js
rtl.js
server/controllers/shared/pageSettings.ts
server/utils/app.ts
server/utils/common.ts
server/utils/config.ts
server/utils/database.ts

Make db location configurable #1177

Make db location configurable #1177

---

backend/controllers/eclair/channels.js
backend/controllers/eclair/invoices.js
backend/controllers/eclair/network.js
backend/controllers/eclair/payments.js
server/controllers/eclair/channels.ts
server/controllers/eclair/invoices.ts
server/controllers/eclair/network.ts
server/controllers/eclair/payments.ts

Fixing Server lint bugs

---

.github/workflows/ci.yml

Fix Artifact Build via Gihtub Actions

Update action versions for ci workflow
